resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - templates/agent_daemonset.yaml
  - templates/agent_service.yaml
  - templates/scheduler_configmap.yaml
  - templates/scheduler_deployment.yaml
  - templates/scheduler_service.yaml
  name: templates
