apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecc
data:
  config.yaml: |
    global:
      logLevel: info
    agent:
      usageLimits:
        concurrentProcessLimit: -1
      schedulerAddress: kubecc-scheduler:9090
      monitorAddress: kubecc-monitor:9090
    scheduler:
      monitorAddress: kubecc-monitor:9090
      cacheAddress: kubecc-cache:9090
      listenAddress: :9090
    monitor:
      listenAddress: :9090
    cache:
      monitorAddress: kubecc-monitor:9090
      listenAddress: :9090
{{ if .Spec.Cache.VolatileStorage }}
      volatileStorage:
{{ .Spec.Cache.VolatileStorage | toYaml | indent 8 }}
{{ end }}
{{ if .Spec.Cache.LocalStorage }}
      localStorage:
{{ .Spec.Cache.LocalStorage | toYaml | indent 8 }}
{{ end }}
{{ if .Spec.Cache.RemoteStorage }}
      remoteStorage:
{{ .Spec.Cache.RemoteStorage | toYaml | indent 8 }}
{{ end }}