apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecc-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecc-scheduler
  template:
    metadata:
      labels: 
        app: kubecc-scheduler
    spec:
{{ if .Spec.NodeAffinity }}
      affinity:
        nodeAffinity:
{{ .Spec.NodeAffinity | toYaml | indent 10 }}
{{ end }}
      containers:
        - name: kubecc-scheduler
          command:
            - /kubecc
            - run
            - scheduler
          image: {{ .Spec.Image }}
          imagePullPolicy: {{ .Spec.ImagePullPolicy }}
{{ if .Spec.Resources }}
          resources:
{{ .Spec.Resources | toYaml | indent 12 }}
{{ end }}
          env:
            - name: KUBECC_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBECC_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBECC_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: grpc
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/kubecc
      volumes:
        - name: config
          configMap:
            name: kubecc
            items:
              - key: config.yaml
                path: config.yaml