# permissions for end users to view buildclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildcluster-viewer-role
rules:
- apiGroups:
  - kubecc.io
  resources:
  - buildclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubecc.io
  resources:
  - buildclusters/status
  verbs:
  - get
