# permissions for end users to edit buildclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildcluster-editor-role
rules:
- apiGroups:
  - kubecc.io
  resources:
  - buildclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecc.io
  resources:
  - buildclusters/status
  verbs:
  - get
