# permissions for end users to view kubeccs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecc-viewer-role
rules:
- apiGroups:
  - kubecc.io
  resources:
  - kubeccs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubecc.io
  resources:
  - kubeccs/status
  verbs:
  - get
