# permissions for end users to edit kubeccs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecc-editor-role
rules:
- apiGroups:
  - kubecc.io
  resources:
  - kubeccs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecc.io
  resources:
  - kubeccs/status
  verbs:
  - get
