# permissions for end users to edit toolchains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toolchain-editor-role
rules:
- apiGroups:
  - kubecc.io
  resources:
  - toolchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecc.io
  resources:
  - toolchains/status
  verbs:
  - get
