apiVersion: kubecc.io/v1alpha1
kind: BuildCluster
metadata:
  name: buildcluster-sample
  namespace: kubecc
spec:
  deployToolbox: true
  toolchains:
    - kind: gcc
      version: "11.1.0"
  components:
    cache:
      localStorage:
        path: /opt/kubecc/cache
        limits:
          disk: "10Gi"
    agent:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubecc.io/role
                  operator: NotIn
                  values:
                    - control-plane
