apiVersion: kubecc.io/v1alpha1
kind: BuildCluster
metadata:
  name: buildcluster-sample
  namespace: kubecc
spec:
  components:
    image: kubecc/kubecc:testing
    imagePullPolicy: Always
    agents:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: allow-kubecc
                operator: In
                values: 
                  - "true"
      resources:
        limits:
          memory: "8Gi"
      image: kubecc/environment:latest
      imagePullPolicy: Always