# permissions for end users to edit distccs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distcc-editor-role
rules:
- apiGroups:
  - kdistcc.io
  resources:
  - distccs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kdistcc.io
  resources:
  - distccs/status
  verbs:
  - get
