// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: proto/types.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Component int32

const (
	Component_Component_Unknown_ Component = 0
	Component_Agent_             Component = 1
	Component_Scheduler_         Component = 2
	Component_Controller_        Component = 3
	Component_Consumer_          Component = 4
	Component_Consumerd_         Component = 5
	Component_Make_              Component = 6
	Component_Test_              Component = 7
	Component_Dashboard_         Component = 8
)

// Enum value maps for Component.
var (
	Component_name = map[int32]string{
		0: "Component_Unknown_",
		1: "Agent_",
		2: "Scheduler_",
		3: "Controller_",
		4: "Consumer_",
		5: "Consumerd_",
		6: "Make_",
		7: "Test_",
		8: "Dashboard_",
	}
	Component_value = map[string]int32{
		"Component_Unknown_": 0,
		"Agent_":             1,
		"Scheduler_":         2,
		"Controller_":        3,
		"Consumer_":          4,
		"Consumerd_":         5,
		"Make_":              6,
		"Test_":              7,
		"Dashboard_":         8,
	}
)

func (x Component) Enum() *Component {
	p := new(Component)
	*p = x
	return p
}

func (x Component) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Component) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[0].Descriptor()
}

func (Component) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[0]
}

func (x Component) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Component.Descriptor instead.
func (Component) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

type QueueStatus int32

const (
	QueueStatus_Available     QueueStatus = 0
	QueueStatus_Queueing      QueueStatus = 1
	QueueStatus_QueuePressure QueueStatus = 2
	QueueStatus_QueueFull     QueueStatus = 3
)

// Enum value maps for QueueStatus.
var (
	QueueStatus_name = map[int32]string{
		0: "Available",
		1: "Queueing",
		2: "QueuePressure",
		3: "QueueFull",
	}
	QueueStatus_value = map[string]int32{
		"Available":     0,
		"Queueing":      1,
		"QueuePressure": 2,
		"QueueFull":     3,
	}
)

func (x QueueStatus) Enum() *QueueStatus {
	p := new(QueueStatus)
	*p = x
	return p
}

func (x QueueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[1].Descriptor()
}

func (QueueStatus) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[1]
}

func (x QueueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueStatus.Descriptor instead.
func (QueueStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

type ToolchainKind int32

const (
	ToolchainKind_ToolchainKind_Unknown_ ToolchainKind = 0
	ToolchainKind_Gnu_                   ToolchainKind = 1
	ToolchainKind_Clang_                 ToolchainKind = 2
)

// Enum value maps for ToolchainKind.
var (
	ToolchainKind_name = map[int32]string{
		0: "ToolchainKind_Unknown_",
		1: "Gnu_",
		2: "Clang_",
	}
	ToolchainKind_value = map[string]int32{
		"ToolchainKind_Unknown_": 0,
		"Gnu_":                   1,
		"Clang_":                 2,
	}
)

func (x ToolchainKind) Enum() *ToolchainKind {
	p := new(ToolchainKind)
	*p = x
	return p
}

func (x ToolchainKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolchainKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[2].Descriptor()
}

func (ToolchainKind) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[2]
}

func (x ToolchainKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolchainKind.Descriptor instead.
func (ToolchainKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

type ToolchainLang int32

const (
	ToolchainLang_ToolchainLang_Unknown_ ToolchainLang = 0
	ToolchainLang_C_                     ToolchainLang = 1
	ToolchainLang_CXX_                   ToolchainLang = 2
	ToolchainLang_Multi_                 ToolchainLang = 3
)

// Enum value maps for ToolchainLang.
var (
	ToolchainLang_name = map[int32]string{
		0: "ToolchainLang_Unknown_",
		1: "C_",
		2: "CXX_",
		3: "Multi_",
	}
	ToolchainLang_value = map[string]int32{
		"ToolchainLang_Unknown_": 0,
		"C_":                     1,
		"CXX_":                   2,
		"Multi_":                 3,
	}
)

func (x ToolchainLang) Enum() *ToolchainLang {
	p := new(ToolchainLang)
	*p = x
	return p
}

func (x ToolchainLang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolchainLang) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[3].Descriptor()
}

func (ToolchainLang) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[3]
}

func (x ToolchainLang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolchainLang.Descriptor instead.
func (ToolchainLang) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

type CompileResponse_Result int32

const (
	CompileResponse_Success CompileResponse_Result = 0
	CompileResponse_Fail    CompileResponse_Result = 1
)

// Enum value maps for CompileResponse_Result.
var (
	CompileResponse_Result_name = map[int32]string{
		0: "Success",
		1: "Fail",
	}
	CompileResponse_Result_value = map[string]int32{
		"Success": 0,
		"Fail":    1,
	}
)

func (x CompileResponse_Result) Enum() *CompileResponse_Result {
	p := new(CompileResponse_Result)
	*p = x
	return p
}

func (x CompileResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompileResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[4].Descriptor()
}

func (CompileResponse_Result) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[4]
}

func (x CompileResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompileResponse_Result.Descriptor instead.
func (CompileResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{15, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

type CpuConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxRunningProcesses    int32   `protobuf:"varint,1,opt,name=MaxRunningProcesses,proto3" json:"MaxRunningProcesses,omitempty"`
	QueuePressureThreshold float64 `protobuf:"fixed64,2,opt,name=QueuePressureThreshold,proto3" json:"QueuePressureThreshold,omitempty"`
	QueueRejectThreshold   float64 `protobuf:"fixed64,3,opt,name=QueueRejectThreshold,proto3" json:"QueueRejectThreshold,omitempty"`
}

func (x *CpuConfig) Reset() {
	*x = CpuConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuConfig) ProtoMessage() {}

func (x *CpuConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuConfig.ProtoReflect.Descriptor instead.
func (*CpuConfig) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *CpuConfig) GetMaxRunningProcesses() int32 {
	if x != nil {
		return x.MaxRunningProcesses
	}
	return 0
}

func (x *CpuConfig) GetQueuePressureThreshold() float64 {
	if x != nil {
		return x.QueuePressureThreshold
	}
	return 0
}

func (x *CpuConfig) GetQueueRejectThreshold() float64 {
	if x != nil {
		return x.QueueRejectThreshold
	}
	return 0
}

type SystemStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusItems []*ComponentStatus `protobuf:"bytes,1,rep,name=StatusItems,proto3" json:"StatusItems,omitempty"`
}

func (x *SystemStatusResponse) Reset() {
	*x = SystemStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatusResponse) ProtoMessage() {}

func (x *SystemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatusResponse.ProtoReflect.Descriptor instead.
func (*SystemStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *SystemStatusResponse) GetStatusItems() []*ComponentStatus {
	if x != nil {
		return x.StatusItems
	}
	return nil
}

type ComponentStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Component Component `protobuf:"varint,1,opt,name=Component,proto3,enum=Component" json:"Component,omitempty"`
	Alive     bool      `protobuf:"varint,2,opt,name=Alive,proto3" json:"Alive,omitempty"`
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *ComponentStatus) GetComponent() Component {
	if x != nil {
		return x.Component
	}
	return Component_Component_Unknown_
}

func (x *ComponentStatus) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type Toolchains struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Toolchain `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *Toolchains) Reset() {
	*x = Toolchains{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toolchains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolchains) ProtoMessage() {}

func (x *Toolchains) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolchains.ProtoReflect.Descriptor instead.
func (*Toolchains) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{4}
}

func (x *Toolchains) GetItems() []*Toolchain {
	if x != nil {
		return x.Items
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Contents:
	//	*Metadata_Toolchains
	//	*Metadata_QueueStatus
	Contents isMetadata_Contents `protobuf_oneof:"Contents"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{5}
}

func (m *Metadata) GetContents() isMetadata_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (x *Metadata) GetToolchains() *Toolchains {
	if x, ok := x.GetContents().(*Metadata_Toolchains); ok {
		return x.Toolchains
	}
	return nil
}

func (x *Metadata) GetQueueStatus() QueueStatus {
	if x, ok := x.GetContents().(*Metadata_QueueStatus); ok {
		return x.QueueStatus
	}
	return QueueStatus_Available
}

type isMetadata_Contents interface {
	isMetadata_Contents()
}

type Metadata_Toolchains struct {
	Toolchains *Toolchains `protobuf:"bytes,2,opt,name=Toolchains,proto3,oneof"`
}

type Metadata_QueueStatus struct {
	QueueStatus QueueStatus `protobuf:"varint,3,opt,name=QueueStatus,proto3,enum=QueueStatus,oneof"`
}

func (*Metadata_Toolchains) isMetadata_Contents() {}

func (*Metadata_QueueStatus) isMetadata_Contents() {}

type Toolchain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind       ToolchainKind `protobuf:"varint,1,opt,name=Kind,proto3,enum=ToolchainKind" json:"Kind,omitempty"`
	Lang       ToolchainLang `protobuf:"varint,2,opt,name=Lang,proto3,enum=ToolchainLang" json:"Lang,omitempty"`
	Executable string        `protobuf:"bytes,3,opt,name=Executable,proto3" json:"Executable,omitempty"`
	TargetArch string        `protobuf:"bytes,4,opt,name=TargetArch,proto3" json:"TargetArch,omitempty"`
	Version    string        `protobuf:"bytes,5,opt,name=Version,proto3" json:"Version,omitempty"`
	PicDefault bool          `protobuf:"varint,6,opt,name=PicDefault,proto3" json:"PicDefault,omitempty"`
}

func (x *Toolchain) Reset() {
	*x = Toolchain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toolchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolchain) ProtoMessage() {}

func (x *Toolchain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolchain.ProtoReflect.Descriptor instead.
func (*Toolchain) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{6}
}

func (x *Toolchain) GetKind() ToolchainKind {
	if x != nil {
		return x.Kind
	}
	return ToolchainKind_ToolchainKind_Unknown_
}

func (x *Toolchain) GetLang() ToolchainLang {
	if x != nil {
		return x.Lang
	}
	return ToolchainLang_ToolchainLang_Unknown_
}

func (x *Toolchain) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *Toolchain) GetTargetArch() string {
	if x != nil {
		return x.TargetArch
	}
	return ""
}

func (x *Toolchain) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Toolchain) GetPicDefault() bool {
	if x != nil {
		return x.PicDefault
	}
	return false
}

type AgentToolchainInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string   `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Target   string   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	Versions []string `protobuf:"bytes,3,rep,name=Versions,proto3" json:"Versions,omitempty"`
}

func (x *AgentToolchainInfo) Reset() {
	*x = AgentToolchainInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentToolchainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToolchainInfo) ProtoMessage() {}

func (x *AgentToolchainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToolchainInfo.ProtoReflect.Descriptor instead.
func (*AgentToolchainInfo) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{7}
}

func (x *AgentToolchainInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentToolchainInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AgentToolchainInfo) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type AgentToolchainInfoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []*AgentToolchainInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *AgentToolchainInfoList) Reset() {
	*x = AgentToolchainInfoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentToolchainInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToolchainInfoList) ProtoMessage() {}

func (x *AgentToolchainInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToolchainInfoList.ProtoReflect.Descriptor instead.
func (*AgentToolchainInfoList) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{8}
}

func (x *AgentToolchainInfoList) GetInfo() []*AgentToolchainInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// consumer -> consumerd
type RunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Compiler:
	//	*RunRequest_Path
	//	*RunRequest_Toolchain
	Compiler isRunRequest_Compiler `protobuf_oneof:"Compiler"`
	Args     []string              `protobuf:"bytes,3,rep,name=Args,proto3" json:"Args,omitempty"`
	UID      uint32                `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`
	GID      uint32                `protobuf:"varint,5,opt,name=GID,proto3" json:"GID,omitempty"`
	WorkDir  string                `protobuf:"bytes,6,opt,name=WorkDir,proto3" json:"WorkDir,omitempty"`
	Env      []string              `protobuf:"bytes,7,rep,name=Env,proto3" json:"Env,omitempty"`
	Stdin    []byte                `protobuf:"bytes,8,opt,name=Stdin,proto3" json:"Stdin,omitempty"`
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{9}
}

func (m *RunRequest) GetCompiler() isRunRequest_Compiler {
	if m != nil {
		return m.Compiler
	}
	return nil
}

func (x *RunRequest) GetPath() string {
	if x, ok := x.GetCompiler().(*RunRequest_Path); ok {
		return x.Path
	}
	return ""
}

func (x *RunRequest) GetToolchain() *Toolchain {
	if x, ok := x.GetCompiler().(*RunRequest_Toolchain); ok {
		return x.Toolchain
	}
	return nil
}

func (x *RunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunRequest) GetUID() uint32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *RunRequest) GetGID() uint32 {
	if x != nil {
		return x.GID
	}
	return 0
}

func (x *RunRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *RunRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type isRunRequest_Compiler interface {
	isRunRequest_Compiler()
}

type RunRequest_Path struct {
	Path string `protobuf:"bytes,1,opt,name=Path,proto3,oneof"`
}

type RunRequest_Toolchain struct {
	Toolchain *Toolchain `protobuf:"bytes,2,opt,name=Toolchain,proto3,oneof"`
}

func (*RunRequest_Path) isRunRequest_Compiler() {}

func (*RunRequest_Toolchain) isRunRequest_Compiler() {}

// consumerd -> consumer
type RunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnCode int32  `protobuf:"varint,1,opt,name=ReturnCode,proto3" json:"ReturnCode,omitempty"`
	Stdout     []byte `protobuf:"bytes,2,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	Stderr     []byte `protobuf:"bytes,3,opt,name=Stderr,proto3" json:"Stderr,omitempty"`
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{10}
}

func (x *RunResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *RunResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RunResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

// consumerd -> scheduler
type ScheduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{11}
}

// scheduler -> consumerd
type ScheduleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{12}
}

type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// System Info
	Arch string `protobuf:"bytes,1,opt,name=Arch,proto3" json:"Arch,omitempty"`
	// Downward API
	Node      string `protobuf:"bytes,3,opt,name=Node,proto3" json:"Node,omitempty"`
	Pod       string `protobuf:"bytes,4,opt,name=Pod,proto3" json:"Pod,omitempty"`
	Namespace string `protobuf:"bytes,5,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{13}
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AgentInfo) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *AgentInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// consumerd -> scheduler -> agent
type CompileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toolchain          *Toolchain `protobuf:"bytes,1,opt,name=Toolchain,proto3" json:"Toolchain,omitempty"`
	Args               []string   `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty"`
	PreprocessedSource []byte     `protobuf:"bytes,3,opt,name=PreprocessedSource,proto3" json:"PreprocessedSource,omitempty"`
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{14}
}

func (x *CompileRequest) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *CompileRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CompileRequest) GetPreprocessedSource() []byte {
	if x != nil {
		return x.PreprocessedSource
	}
	return nil
}

// agent -> scheduler -> consumerd
type CompileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompileResult CompileResponse_Result `protobuf:"varint,1,opt,name=CompileResult,proto3,enum=CompileResponse_Result" json:"CompileResult,omitempty"`
	// Types that are assignable to Data:
	//	*CompileResponse_Error
	//	*CompileResponse_CompiledSource
	Data isCompileResponse_Data `protobuf_oneof:"Data"`
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{15}
}

func (x *CompileResponse) GetCompileResult() CompileResponse_Result {
	if x != nil {
		return x.CompileResult
	}
	return CompileResponse_Success
}

func (m *CompileResponse) GetData() isCompileResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *CompileResponse) GetError() string {
	if x, ok := x.GetData().(*CompileResponse_Error); ok {
		return x.Error
	}
	return ""
}

func (x *CompileResponse) GetCompiledSource() []byte {
	if x, ok := x.GetData().(*CompileResponse_CompiledSource); ok {
		return x.CompiledSource
	}
	return nil
}

type isCompileResponse_Data interface {
	isCompileResponse_Data()
}

type CompileResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=Error,proto3,oneof"`
}

type CompileResponse_CompiledSource struct {
	CompiledSource []byte `protobuf:"bytes,4,opt,name=CompiledSource,proto3,oneof"`
}

func (*CompileResponse_Error) isCompileResponse_Data() {}

func (*CompileResponse_CompiledSource) isCompileResponse_Data() {}

var File_proto_types_proto protoreflect.FileDescriptor

var file_proto_types_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xa9, 0x01, 0x0a,
	0x09, 0x43, 0x70, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x30, 0x0a, 0x13, 0x4d, 0x61,
	0x78, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x4d, 0x61, 0x78, 0x52, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x16,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x54, 0x68, 0x72,
	0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x16, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x12, 0x32, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x14, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x54,
	0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x51, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x2e, 0x0a, 0x0a, 0x54, 0x6f, 0x6f, 0x6c, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x77, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x0a, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xcd, 0x01, 0x0a, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x22,
	0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x54,
	0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x61, 0x6e, 0x67,
	0x52, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x41, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x41, 0x72, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x69, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x50, 0x69, 0x63, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x22, 0x5c, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x41,
	0x0a, 0x16, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f,
	0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0xd4, 0x01, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2a, 0x0a, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x6f, 0x6f, 0x6c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x41, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x49, 0x44, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x47, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x6f,
	0x72, 0x6b, 0x44, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x57, 0x6f, 0x72,
	0x6b, 0x44, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x64, 0x69, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x53, 0x74, 0x64, 0x69, 0x6e, 0x42, 0x0a, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x63,
	0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x63, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0x7e, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x52, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x50, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x12, 0x50, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x2a, 0x95, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72,
	0x5f, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x5f, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x64,
	0x5f, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x61, 0x6b, 0x65, 0x5f, 0x10, 0x06, 0x12, 0x09,
	0x0a, 0x05, 0x54, 0x65, 0x73, 0x74, 0x5f, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x61, 0x73,
	0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x10, 0x08, 0x2a, 0x4c, 0x0a, 0x0b, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x72,
	0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x03, 0x2a, 0x41, 0x0a, 0x0d, 0x54, 0x6f, 0x6f, 0x6c, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x6f, 0x6f, 0x6c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x5f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x6e, 0x75, 0x5f, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x6c, 0x61, 0x6e, 0x67, 0x5f, 0x10, 0x02, 0x2a, 0x49, 0x0a, 0x0d, 0x54, 0x6f,
	0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x16, 0x54,
	0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4c, 0x61, 0x6e, 0x67, 0x5f, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x43, 0x5f, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x43, 0x58, 0x58, 0x5f, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x5f, 0x10, 0x03, 0x32, 0x2d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x0b, 0x2e, 0x52, 0x75, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7d, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a,
	0x07, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x43, 0x70, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x43, 0x70, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x22, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x43, 0x70, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x0a, 0x2e, 0x43, 0x70, 0x75, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0xba, 0x01, 0x0a, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x72, 0x12, 0x2c, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x09, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x28, 0x01, 0x30, 0x01, 0x12, 0x29, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x64, 0x12, 0x09, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x2d, 0x0a, 0x0c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0b, 0x5a, 0x09, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_types_proto_rawDescOnce sync.Once
	file_proto_types_proto_rawDescData = file_proto_types_proto_rawDesc
)

func file_proto_types_proto_rawDescGZIP() []byte {
	file_proto_types_proto_rawDescOnce.Do(func() {
		file_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_types_proto_rawDescData)
	})
	return file_proto_types_proto_rawDescData
}

var file_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_types_proto_goTypes = []interface{}{
	(Component)(0),                 // 0: Component
	(QueueStatus)(0),               // 1: QueueStatus
	(ToolchainKind)(0),             // 2: ToolchainKind
	(ToolchainLang)(0),             // 3: ToolchainLang
	(CompileResponse_Result)(0),    // 4: CompileResponse.Result
	(*Empty)(nil),                  // 5: Empty
	(*CpuConfig)(nil),              // 6: CpuConfig
	(*SystemStatusResponse)(nil),   // 7: SystemStatusResponse
	(*ComponentStatus)(nil),        // 8: ComponentStatus
	(*Toolchains)(nil),             // 9: Toolchains
	(*Metadata)(nil),               // 10: Metadata
	(*Toolchain)(nil),              // 11: Toolchain
	(*AgentToolchainInfo)(nil),     // 12: AgentToolchainInfo
	(*AgentToolchainInfoList)(nil), // 13: AgentToolchainInfoList
	(*RunRequest)(nil),             // 14: RunRequest
	(*RunResponse)(nil),            // 15: RunResponse
	(*ScheduleRequest)(nil),        // 16: ScheduleRequest
	(*ScheduleResponse)(nil),       // 17: ScheduleResponse
	(*AgentInfo)(nil),              // 18: AgentInfo
	(*CompileRequest)(nil),         // 19: CompileRequest
	(*CompileResponse)(nil),        // 20: CompileResponse
}
var file_proto_types_proto_depIdxs = []int32{
	8,  // 0: SystemStatusResponse.StatusItems:type_name -> ComponentStatus
	0,  // 1: ComponentStatus.Component:type_name -> Component
	11, // 2: Toolchains.Items:type_name -> Toolchain
	9,  // 3: Metadata.Toolchains:type_name -> Toolchains
	1,  // 4: Metadata.QueueStatus:type_name -> QueueStatus
	2,  // 5: Toolchain.Kind:type_name -> ToolchainKind
	3,  // 6: Toolchain.Lang:type_name -> ToolchainLang
	12, // 7: AgentToolchainInfoList.info:type_name -> AgentToolchainInfo
	11, // 8: RunRequest.Toolchain:type_name -> Toolchain
	11, // 9: CompileRequest.Toolchain:type_name -> Toolchain
	4,  // 10: CompileResponse.CompileResult:type_name -> CompileResponse.Result
	14, // 11: Consumerd.Run:input_type -> RunRequest
	19, // 12: Agent.Compile:input_type -> CompileRequest
	5,  // 13: Agent.GetCpuConfig:input_type -> Empty
	6,  // 14: Agent.SetCpuConfig:input_type -> CpuConfig
	19, // 15: Scheduler.Compile:input_type -> CompileRequest
	10, // 16: Scheduler.ConnectAgent:input_type -> Metadata
	10, // 17: Scheduler.ConnectConsumerd:input_type -> Metadata
	5,  // 18: Scheduler.SystemStatus:input_type -> Empty
	15, // 19: Consumerd.Run:output_type -> RunResponse
	20, // 20: Agent.Compile:output_type -> CompileResponse
	6,  // 21: Agent.GetCpuConfig:output_type -> CpuConfig
	5,  // 22: Agent.SetCpuConfig:output_type -> Empty
	20, // 23: Scheduler.Compile:output_type -> CompileResponse
	5,  // 24: Scheduler.ConnectAgent:output_type -> Empty
	5,  // 25: Scheduler.ConnectConsumerd:output_type -> Empty
	7,  // 26: Scheduler.SystemStatus:output_type -> SystemStatusResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_types_proto_init() }
func file_proto_types_proto_init() {
	if File_proto_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toolchains); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toolchain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentToolchainInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentToolchainInfoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_types_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Metadata_Toolchains)(nil),
		(*Metadata_QueueStatus)(nil),
	}
	file_proto_types_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*RunRequest_Path)(nil),
		(*RunRequest_Toolchain)(nil),
	}
	file_proto_types_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*CompileResponse_Error)(nil),
		(*CompileResponse_CompiledSource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_types_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_types_proto_goTypes,
		DependencyIndexes: file_proto_types_proto_depIdxs,
		EnumInfos:         file_proto_types_proto_enumTypes,
		MessageInfos:      file_proto_types_proto_msgTypes,
	}.Build()
	File_proto_types_proto = out.File
	file_proto_types_proto_rawDesc = nil
	file_proto_types_proto_goTypes = nil
	file_proto_types_proto_depIdxs = nil
}
