// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.16.0
// source: pkg/metrics/metrics.proto

package metrics

import (
	proto "github.com/golang/protobuf/proto"
	types "github.com/kubecc-io/kubecc/pkg/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OverallStatus int32

const (
	OverallStatus_UnknownStatus OverallStatus = 0
	OverallStatus_Ready         OverallStatus = 1
	OverallStatus_Initializing  OverallStatus = 2
	OverallStatus_Degraded      OverallStatus = 3
	OverallStatus_Unavailable   OverallStatus = 4
)

// Enum value maps for OverallStatus.
var (
	OverallStatus_name = map[int32]string{
		0: "UnknownStatus",
		1: "Ready",
		2: "Initializing",
		3: "Degraded",
		4: "Unavailable",
	}
	OverallStatus_value = map[string]int32{
		"UnknownStatus": 0,
		"Ready":         1,
		"Initializing":  2,
		"Degraded":      3,
		"Unavailable":   4,
	}
)

func (x OverallStatus) Enum() *OverallStatus {
	p := new(OverallStatus)
	*p = x
	return p
}

func (x OverallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_metrics_metrics_proto_enumTypes[0].Descriptor()
}

func (OverallStatus) Type() protoreflect.EnumType {
	return &file_pkg_metrics_metrics_proto_enumTypes[0]
}

func (x OverallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverallStatus.Descriptor instead.
func (OverallStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

type StatusConditions int32

const (
	StatusConditions_NoConditions             StatusConditions = 0
	StatusConditions_Pending                  StatusConditions = 1
	StatusConditions_MissingOptionalComponent StatusConditions = 2
	StatusConditions_MissingCriticalComponent StatusConditions = 3
	StatusConditions_InvalidConfiguration     StatusConditions = 4
	StatusConditions_InternalError            StatusConditions = 5
)

// Enum value maps for StatusConditions.
var (
	StatusConditions_name = map[int32]string{
		0: "NoConditions",
		1: "Pending",
		2: "MissingOptionalComponent",
		3: "MissingCriticalComponent",
		4: "InvalidConfiguration",
		5: "InternalError",
	}
	StatusConditions_value = map[string]int32{
		"NoConditions":             0,
		"Pending":                  1,
		"MissingOptionalComponent": 2,
		"MissingCriticalComponent": 3,
		"InvalidConfiguration":     4,
		"InternalError":            5,
	}
)

func (x StatusConditions) Enum() *StatusConditions {
	p := new(StatusConditions)
	*p = x
	return p
}

func (x StatusConditions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusConditions) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_metrics_metrics_proto_enumTypes[1].Descriptor()
}

func (StatusConditions) Type() protoreflect.EnumType {
	return &file_pkg_metrics_metrics_proto_enumTypes[1]
}

func (x StatusConditions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusConditions.Descriptor instead.
func (StatusConditions) EnumDescriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

type TaskStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRunning   int32 `protobuf:"varint,1,opt,name=NumRunning,proto3" json:"NumRunning,omitempty"`
	NumQueued    int32 `protobuf:"varint,2,opt,name=NumQueued,proto3" json:"NumQueued,omitempty"`
	NumDelegated int32 `protobuf:"varint,3,opt,name=NumDelegated,proto3" json:"NumDelegated,omitempty"`
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *TaskStatus) GetNumRunning() int32 {
	if x != nil {
		return x.NumRunning
	}
	return 0
}

func (x *TaskStatus) GetNumQueued() int32 {
	if x != nil {
		return x.NumQueued
	}
	return 0
}

func (x *TaskStatus) GetNumDelegated() int32 {
	if x != nil {
		return x.NumDelegated
	}
	return 0
}

type Toolchains struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*types.Toolchain `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *Toolchains) Reset() {
	*x = Toolchains{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toolchains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolchains) ProtoMessage() {}

func (x *Toolchains) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolchains.ProtoReflect.Descriptor instead.
func (*Toolchains) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Toolchains) GetItems() []*types.Toolchain {
	if x != nil {
		return x.Items
	}
	return nil
}

type UsageLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConcurrentProcessLimit int32 `protobuf:"varint,1,opt,name=ConcurrentProcessLimit,proto3" json:"ConcurrentProcessLimit,omitempty"`
	DelegatedTaskLimit     int32 `protobuf:"varint,2,opt,name=DelegatedTaskLimit,proto3" json:"DelegatedTaskLimit,omitempty"`
}

func (x *UsageLimits) Reset() {
	*x = UsageLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageLimits) ProtoMessage() {}

func (x *UsageLimits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageLimits.ProtoReflect.Descriptor instead.
func (*UsageLimits) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *UsageLimits) GetConcurrentProcessLimit() int32 {
	if x != nil {
		return x.ConcurrentProcessLimit
	}
	return 0
}

func (x *UsageLimits) GetDelegatedTaskLimit() int32 {
	if x != nil {
		return x.DelegatedTaskLimit
	}
	return 0
}

type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      string `protobuf:"bytes,4,opt,name=Node,proto3" json:"Node,omitempty"`
	Pod       string `protobuf:"bytes,5,opt,name=Pod,proto3" json:"Pod,omitempty"`
	Namespace string `protobuf:"bytes,6,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AgentInfo) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *AgentInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Deleter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *Deleter) Reset() {
	*x = Deleter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deleter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deleter) ProtoMessage() {}

func (x *Deleter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deleter.ProtoReflect.Descriptor instead.
func (*Deleter) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *Deleter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CpuStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WallTime       uint64          `protobuf:"varint,1,opt,name=WallTime,proto3" json:"WallTime,omitempty"`
	CpuUsage       *CpuUsage       `protobuf:"bytes,2,opt,name=CpuUsage,proto3" json:"CpuUsage,omitempty"`
	ThrottlingData *ThrottlingData `protobuf:"bytes,3,opt,name=ThrottlingData,proto3" json:"ThrottlingData,omitempty"`
}

func (x *CpuStats) Reset() {
	*x = CpuStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuStats) ProtoMessage() {}

func (x *CpuStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuStats.ProtoReflect.Descriptor instead.
func (*CpuStats) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *CpuStats) GetWallTime() uint64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *CpuStats) GetCpuUsage() *CpuUsage {
	if x != nil {
		return x.CpuUsage
	}
	return nil
}

func (x *CpuStats) GetThrottlingData() *ThrottlingData {
	if x != nil {
		return x.ThrottlingData
	}
	return nil
}

type CpuUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfsQuota   int64  `protobuf:"varint,1,opt,name=CfsQuota,proto3" json:"CfsQuota,omitempty"`
	CfsPeriod  int64  `protobuf:"varint,2,opt,name=CfsPeriod,proto3" json:"CfsPeriod,omitempty"`
	TotalUsage uint64 `protobuf:"varint,3,opt,name=TotalUsage,proto3" json:"TotalUsage,omitempty"`
}

func (x *CpuUsage) Reset() {
	*x = CpuUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuUsage) ProtoMessage() {}

func (x *CpuUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuUsage.ProtoReflect.Descriptor instead.
func (*CpuUsage) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *CpuUsage) GetCfsQuota() int64 {
	if x != nil {
		return x.CfsQuota
	}
	return 0
}

func (x *CpuUsage) GetCfsPeriod() int64 {
	if x != nil {
		return x.CfsPeriod
	}
	return 0
}

func (x *CpuUsage) GetTotalUsage() uint64 {
	if x != nil {
		return x.TotalUsage
	}
	return 0
}

// libcontainer/cgroups/stats.go ThrottlingData
type ThrottlingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Periods          uint64 `protobuf:"varint,1,opt,name=Periods,proto3" json:"Periods,omitempty"`
	ThrottledPeriods uint64 `protobuf:"varint,2,opt,name=ThrottledPeriods,proto3" json:"ThrottledPeriods,omitempty"`
	ThrottledTime    uint64 `protobuf:"varint,3,opt,name=ThrottledTime,proto3" json:"ThrottledTime,omitempty"`
}

func (x *ThrottlingData) Reset() {
	*x = ThrottlingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThrottlingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrottlingData) ProtoMessage() {}

func (x *ThrottlingData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrottlingData.ProtoReflect.Descriptor instead.
func (*ThrottlingData) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *ThrottlingData) GetPeriods() uint64 {
	if x != nil {
		return x.Periods
	}
	return 0
}

func (x *ThrottlingData) GetThrottledPeriods() uint64 {
	if x != nil {
		return x.ThrottledPeriods
	}
	return 0
}

func (x *ThrottlingData) GetThrottledTime() uint64 {
	if x != nil {
		return x.ThrottledTime
	}
	return 0
}

type TasksCompletedTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *TasksCompletedTotal) Reset() {
	*x = TasksCompletedTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksCompletedTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksCompletedTotal) ProtoMessage() {}

func (x *TasksCompletedTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksCompletedTotal.ProtoReflect.Descriptor instead.
func (*TasksCompletedTotal) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *TasksCompletedTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TasksFailedTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *TasksFailedTotal) Reset() {
	*x = TasksFailedTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksFailedTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksFailedTotal) ProtoMessage() {}

func (x *TasksFailedTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksFailedTotal.ProtoReflect.Descriptor instead.
func (*TasksFailedTotal) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *TasksFailedTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SchedulingRequestsTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *SchedulingRequestsTotal) Reset() {
	*x = SchedulingRequestsTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedulingRequestsTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingRequestsTotal) ProtoMessage() {}

func (x *SchedulingRequestsTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingRequestsTotal.ProtoReflect.Descriptor instead.
func (*SchedulingRequestsTotal) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *SchedulingRequestsTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AgentCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *AgentCount) Reset() {
	*x = AgentCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCount) ProtoMessage() {}

func (x *AgentCount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCount.ProtoReflect.Descriptor instead.
func (*AgentCount) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *AgentCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConsumerdCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *ConsumerdCount) Reset() {
	*x = ConsumerdCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerdCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerdCount) ProtoMessage() {}

func (x *ConsumerdCount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerdCount.ProtoReflect.Descriptor instead.
func (*ConsumerdCount) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumerdCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Identifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{13}
}

func (x *Identifier) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type AgentTasksTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID  string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Total int64  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *AgentTasksTotal) Reset() {
	*x = AgentTasksTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentTasksTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTasksTotal) ProtoMessage() {}

func (x *AgentTasksTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTasksTotal.ProtoReflect.Descriptor instead.
func (*AgentTasksTotal) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{14}
}

func (x *AgentTasksTotal) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *AgentTasksTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConsumerdTasksTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID  string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Total int64  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *ConsumerdTasksTotal) Reset() {
	*x = ConsumerdTasksTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerdTasksTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerdTasksTotal) ProtoMessage() {}

func (x *ConsumerdTasksTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerdTasksTotal.ProtoReflect.Descriptor instead.
func (*ConsumerdTasksTotal) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{15}
}

func (x *ConsumerdTasksTotal) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ConsumerdTasksTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PreferredUsageLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConcurrentProcessLimit int64 `protobuf:"varint,1,opt,name=ConcurrentProcessLimit,proto3" json:"ConcurrentProcessLimit,omitempty"`
}

func (x *PreferredUsageLimits) Reset() {
	*x = PreferredUsageLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreferredUsageLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferredUsageLimits) ProtoMessage() {}

func (x *PreferredUsageLimits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferredUsageLimits.ProtoReflect.Descriptor instead.
func (*PreferredUsageLimits) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{16}
}

func (x *PreferredUsageLimits) GetConcurrentProcessLimit() int64 {
	if x != nil {
		return x.ConcurrentProcessLimit
	}
	return 0
}

type MetricsPostedTotal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *MetricsPostedTotal) Reset() {
	*x = MetricsPostedTotal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsPostedTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPostedTotal) ProtoMessage() {}

func (x *MetricsPostedTotal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPostedTotal.ProtoReflect.Descriptor instead.
func (*MetricsPostedTotal) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{17}
}

func (x *MetricsPostedTotal) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListenerCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *ListenerCount) Reset() {
	*x = ListenerCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenerCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerCount) ProtoMessage() {}

func (x *ListenerCount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerCount.ProtoReflect.Descriptor instead.
func (*ListenerCount) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{18}
}

func (x *ListenerCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProviderCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *ProviderCount) Reset() {
	*x = ProviderCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCount) ProtoMessage() {}

func (x *ProviderCount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCount.ProtoReflect.Descriptor instead.
func (*ProviderCount) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{19}
}

func (x *ProviderCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProviderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID      string          `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Component types.Component `protobuf:"varint,2,opt,name=Component,proto3,enum=types.Component" json:"Component,omitempty"`
	Address   string          `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{20}
}

func (x *ProviderInfo) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ProviderInfo) GetComponent() types.Component {
	if x != nil {
		return x.Component
	}
	return types.Component_Component_Unknown
}

func (x *ProviderInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Providers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]*ProviderInfo `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Providers) Reset() {
	*x = Providers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Providers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Providers) ProtoMessage() {}

func (x *Providers) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Providers.ProtoReflect.Descriptor instead.
func (*Providers) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{21}
}

func (x *Providers) GetItems() map[string]*ProviderInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type BucketSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data map[string]*anypb.Any `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BucketSpec) Reset() {
	*x = BucketSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSpec) ProtoMessage() {}

func (x *BucketSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSpec.ProtoReflect.Descriptor instead.
func (*BucketSpec) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{22}
}

func (x *BucketSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketSpec) GetData() map[string]*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type LocalTasksCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *LocalTasksCompleted) Reset() {
	*x = LocalTasksCompleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalTasksCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTasksCompleted) ProtoMessage() {}

func (x *LocalTasksCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTasksCompleted.ProtoReflect.Descriptor instead.
func (*LocalTasksCompleted) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{23}
}

func (x *LocalTasksCompleted) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DelegatedTasksCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *DelegatedTasksCompleted) Reset() {
	*x = DelegatedTasksCompleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelegatedTasksCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegatedTasksCompleted) ProtoMessage() {}

func (x *DelegatedTasksCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegatedTasksCompleted.ProtoReflect.Descriptor instead.
func (*DelegatedTasksCompleted) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{24}
}

func (x *DelegatedTasksCompleted) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CacheUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectCount  int64   `protobuf:"varint,1,opt,name=ObjectCount,proto3" json:"ObjectCount,omitempty"`
	TotalSize    int64   `protobuf:"varint,2,opt,name=TotalSize,proto3" json:"TotalSize,omitempty"`
	UsagePercent float64 `protobuf:"fixed64,3,opt,name=UsagePercent,proto3" json:"UsagePercent,omitempty"`
}

func (x *CacheUsage) Reset() {
	*x = CacheUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUsage) ProtoMessage() {}

func (x *CacheUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUsage.ProtoReflect.Descriptor instead.
func (*CacheUsage) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{25}
}

func (x *CacheUsage) GetObjectCount() int64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *CacheUsage) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *CacheUsage) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type CacheHits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheHitsTotal   int64   `protobuf:"varint,1,opt,name=CacheHitsTotal,proto3" json:"CacheHitsTotal,omitempty"`
	CacheMissesTotal int64   `protobuf:"varint,2,opt,name=CacheMissesTotal,proto3" json:"CacheMissesTotal,omitempty"`
	CacheHitPercent  float64 `protobuf:"fixed64,3,opt,name=CacheHitPercent,proto3" json:"CacheHitPercent,omitempty"`
}

func (x *CacheHits) Reset() {
	*x = CacheHits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheHits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHits) ProtoMessage() {}

func (x *CacheHits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHits.ProtoReflect.Descriptor instead.
func (*CacheHits) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{26}
}

func (x *CacheHits) GetCacheHitsTotal() int64 {
	if x != nil {
		return x.CacheHitsTotal
	}
	return 0
}

func (x *CacheHits) GetCacheMissesTotal() int64 {
	if x != nil {
		return x.CacheMissesTotal
	}
	return 0
}

func (x *CacheHits) GetCacheHitPercent() float64 {
	if x != nil {
		return x.CacheHitPercent
	}
	return 0
}

type Health struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   OverallStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=metrics.OverallStatus" json:"Status,omitempty"`
	Messages []string      `protobuf:"bytes,3,rep,name=Messages,proto3" json:"Messages,omitempty"`
}

func (x *Health) Reset() {
	*x = Health{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_metrics_metrics_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_metrics_metrics_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_pkg_metrics_metrics_proto_rawDescGZIP(), []int{27}
}

func (x *Health) GetStatus() OverallStatus {
	if x != nil {
		return x.Status
	}
	return OverallStatus_UnknownStatus
}

func (x *Health) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_pkg_metrics_metrics_proto protoreflect.FileDescriptor

var file_pkg_metrics_metrics_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x1a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x75, 0x6d, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4e, 0x75, 0x6d, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x75, 0x6d, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x4e, 0x75, 0x6d, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x44, 0x65, 0x6c,
	0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x22, 0x34, 0x0a, 0x0a, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6f, 0x6c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x75, 0x0a, 0x0b,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x16, 0x43,
	0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x43, 0x6f, 0x6e,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x4f, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x22, 0x96, 0x01, 0x0a, 0x08, 0x43, 0x70, 0x75, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x57, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x57, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x43, 0x70,
	0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x43, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x08, 0x43, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x54, 0x68, 0x72,
	0x6f, 0x74, 0x74, 0x6c, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x54, 0x68, 0x72, 0x6f,
	0x74, 0x74, 0x6c, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x54, 0x68, 0x72, 0x6f,
	0x74, 0x74, 0x6c, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x64, 0x0a, 0x08, 0x43, 0x70,
	0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x66, 0x73, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x66, 0x73, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x66, 0x73, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x66, 0x73, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x7c, 0x0a, 0x0e, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x10,
	0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65,
	0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x68, 0x72, 0x6f,
	0x74, 0x74, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2b,
	0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x28, 0x0a, 0x10, 0x54,
	0x61, 0x73, 0x6b, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x55, 0x55, 0x49, 0x44, 0x22, 0x3b, 0x0a, 0x0f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x4e, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x16, 0x43, 0x6f,
	0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x43, 0x6f, 0x6e, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x50, 0x6f, 0x73,
	0x74, 0x65, 0x64, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x25,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x0c,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x12, 0x2e, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x4f, 0x0a,
	0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa2,
	0x01, 0x0a, 0x0a, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x31, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x4d, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x2b, 0x0a, 0x13, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x2f, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x70, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x22, 0x89, 0x01, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74, 0x73, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x48, 0x69, 0x74, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x43, 0x61, 0x63, 0x68, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x65, 0x73,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69,
	0x74, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x69, 0x74, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x22,
	0x54, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x5e, 0x0a, 0x0d, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x65, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x64, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x10, 0x04, 0x2a, 0x9a, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x04, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x05, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x63, 0x63, 0x2d, 0x69, 0x6f, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x63,
	0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_metrics_metrics_proto_rawDescOnce sync.Once
	file_pkg_metrics_metrics_proto_rawDescData = file_pkg_metrics_metrics_proto_rawDesc
)

func file_pkg_metrics_metrics_proto_rawDescGZIP() []byte {
	file_pkg_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_pkg_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_metrics_metrics_proto_rawDescData)
	})
	return file_pkg_metrics_metrics_proto_rawDescData
}

var file_pkg_metrics_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_pkg_metrics_metrics_proto_goTypes = []interface{}{
	(OverallStatus)(0),              // 0: metrics.OverallStatus
	(StatusConditions)(0),           // 1: metrics.StatusConditions
	(*TaskStatus)(nil),              // 2: metrics.TaskStatus
	(*Toolchains)(nil),              // 3: metrics.Toolchains
	(*UsageLimits)(nil),             // 4: metrics.UsageLimits
	(*AgentInfo)(nil),               // 5: metrics.AgentInfo
	(*Deleter)(nil),                 // 6: metrics.Deleter
	(*CpuStats)(nil),                // 7: metrics.CpuStats
	(*CpuUsage)(nil),                // 8: metrics.CpuUsage
	(*ThrottlingData)(nil),          // 9: metrics.ThrottlingData
	(*TasksCompletedTotal)(nil),     // 10: metrics.TasksCompletedTotal
	(*TasksFailedTotal)(nil),        // 11: metrics.TasksFailedTotal
	(*SchedulingRequestsTotal)(nil), // 12: metrics.SchedulingRequestsTotal
	(*AgentCount)(nil),              // 13: metrics.AgentCount
	(*ConsumerdCount)(nil),          // 14: metrics.ConsumerdCount
	(*Identifier)(nil),              // 15: metrics.Identifier
	(*AgentTasksTotal)(nil),         // 16: metrics.AgentTasksTotal
	(*ConsumerdTasksTotal)(nil),     // 17: metrics.ConsumerdTasksTotal
	(*PreferredUsageLimits)(nil),    // 18: metrics.PreferredUsageLimits
	(*MetricsPostedTotal)(nil),      // 19: metrics.MetricsPostedTotal
	(*ListenerCount)(nil),           // 20: metrics.ListenerCount
	(*ProviderCount)(nil),           // 21: metrics.ProviderCount
	(*ProviderInfo)(nil),            // 22: metrics.ProviderInfo
	(*Providers)(nil),               // 23: metrics.Providers
	(*BucketSpec)(nil),              // 24: metrics.BucketSpec
	(*LocalTasksCompleted)(nil),     // 25: metrics.LocalTasksCompleted
	(*DelegatedTasksCompleted)(nil), // 26: metrics.DelegatedTasksCompleted
	(*CacheUsage)(nil),              // 27: metrics.CacheUsage
	(*CacheHits)(nil),               // 28: metrics.CacheHits
	(*Health)(nil),                  // 29: metrics.Health
	nil,                             // 30: metrics.Providers.ItemsEntry
	nil,                             // 31: metrics.BucketSpec.DataEntry
	(*types.Toolchain)(nil),         // 32: types.Toolchain
	(types.Component)(0),            // 33: types.Component
	(*anypb.Any)(nil),               // 34: google.protobuf.Any
}
var file_pkg_metrics_metrics_proto_depIdxs = []int32{
	32, // 0: metrics.Toolchains.Items:type_name -> types.Toolchain
	8,  // 1: metrics.CpuStats.CpuUsage:type_name -> metrics.CpuUsage
	9,  // 2: metrics.CpuStats.ThrottlingData:type_name -> metrics.ThrottlingData
	33, // 3: metrics.ProviderInfo.Component:type_name -> types.Component
	30, // 4: metrics.Providers.Items:type_name -> metrics.Providers.ItemsEntry
	31, // 5: metrics.BucketSpec.Data:type_name -> metrics.BucketSpec.DataEntry
	0,  // 6: metrics.Health.Status:type_name -> metrics.OverallStatus
	22, // 7: metrics.Providers.ItemsEntry.value:type_name -> metrics.ProviderInfo
	34, // 8: metrics.BucketSpec.DataEntry.value:type_name -> google.protobuf.Any
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_metrics_metrics_proto_init() }
func file_pkg_metrics_metrics_proto_init() {
	if File_pkg_metrics_metrics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_metrics_metrics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toolchains); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsageLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deleter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpuUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThrottlingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksCompletedTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksFailedTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedulingRequestsTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerdCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentTasksTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerdTasksTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreferredUsageLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsPostedTotal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenerCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Providers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalTasksCompleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelegatedTasksCompleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheHits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_metrics_metrics_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Health); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_metrics_metrics_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_pkg_metrics_metrics_proto_depIdxs,
		EnumInfos:         file_pkg_metrics_metrics_proto_enumTypes,
		MessageInfos:      file_pkg_metrics_metrics_proto_msgTypes,
	}.Build()
	File_pkg_metrics_metrics_proto = out.File
	file_pkg_metrics_metrics_proto_rawDesc = nil
	file_pkg_metrics_metrics_proto_goTypes = nil
	file_pkg_metrics_metrics_proto_depIdxs = nil
}
