apiVersion: kdistcc.io/v1alpha1
kind: Distcc
metadata:
  name: distcc-sample
spec:
  nodes:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: allow-distcc
              operator: In
              values: 
                - "true"
    resources:
      requests:
        memory: 500Mi
        cpu: 2
      limits:
        memory: 1Gi
        cpu: 4
  agentImage: kdistcc/agent:testing
  mgrImage: kdistcc/mgr:testing
  ingressStrategy: traefik
  tlsStrategy: cert-manager
  hostname: distcc.example.com

        
