name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go
          restore-keys: |
            ${{ runner.os }}-go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"
      - name: Build
        run: make kubecc
      - name: Test
        run: make test
        env:
          GITHUB_WORKFLOW: "1"
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          files: cover.out
          verbose: true
