name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'

    - name: Build
      env:
        GO: go
      run: make setup && make -j $(nproc)

    - name: Test
      env:
        GO: go
      run: make test-unit
