name: Go

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'

    - name: Build
      run: make setup && make -j $(nproc)

    - name: Unit Tests
      run: make test-unit
      env:
        GITHUB_WORKFLOW: "1"

    - name: Integration Tests
      run: make test-integration
      env:
        GITHUB_WORKFLOW: "1"

